title: ICMLSC 2019
author:
  name: Sri Pravan Paturi
  email: pravanpaturi@gmail.com
subtitle: International Conference on Machine Learning, Security and Cloud Computing
description: ICMLSC 2019 is a conference on Machine Learning, Security and Cloud Computing.