title: ICMLSC 2020
author:
  name: Sri Pravan Paturi, N. Puneet, Akash Rao Mallareddy
  email: pravanpaturi@gmail.com
subtitle: 2nd International Conference on Machine Learning, Security and Cloud Computing
description: ICMLSC 2020 is a conference on Machine Learning, Security and Cloud Computing.
kramdown:
  parse_block_html: true
